# .github/workflows/scheduled-triggerer.yml
name: Trigger Lighthouse run on a CRON Schedule

on:
  schedule:
    # Runs "every hour" (see https://crontab.guru)
    - cron: '0 * * * *'
jobs:
  build:
    name: Trigger Lighthouse
    runs-on: ubuntu-latest
    steps:
      - name: cURL request
        # Hit the endpoint to run lighthouse
        run: curl https://www.google.com